# -*- coding: utf-8 -*-
#
# Configuration file for the stock assessment framework
#

# Replace with your actual API key from Financial Modeling Prep
# Currently not used since data from YF
API_KEY: "O7jpbikr5wCjo34KFLWi9nmU3xJ9laxh"

# The tickers to analyze
tickers:
   - MSFT
   - AAPL
   - GOOGL
   - AMZN
   - TSLA
   - NVDA
   - META
   - ASML
   - AMD
   - ARM
   - JPM
   - GS
   - INTU
   - TSMC34.SA
   - RACE
   - PLTR
   - LLY
   - VRTX
   - KMI
   - C
   - INTC
   - BABA
   - RIO
   - EQR
   - LMT
   - BATS.L
   - ADYEN.AS
   - XYZ
   - CRM
   - SE
   - ORCL
   - ADBE
   - V
   - MA
   - ANET
   - AZO
   - BKNG
   - BN
   - CCJ
   - COIN
   - CSU.TO
   - DELL
   - NVO
   - HIMS
   - INPST.AS
   - MELI
   - MU
   - PYPL
   - RHM.DE
   - NOW
   - SPOT
   - UBER
   - ULTA
   - CMG
   - CRWD
   - OR.PA
   - MCD
   - SBUX
   - NKE
   - ODFL
   - PANW
   - ZAL.DE
   - KER.PA
   - MC.PA
   - SAP
   - AZN
   - UNH
   - BAC

# Set flags whether the data should be pulled online (True) or from local files (False)
use_quant: false
use_qual: false
use_external: true

############################################################ QUANTITATIVE ############################################
# Weights for the quantitative score (ensure they sum to 1.0)
quant_weights:
  revenue_growth:   0.13
  eps_growth:       0.13
  fcf_growth:       0.05
  net_margin_avg:   0.13
  gross_margin_avg: 0.13
  d_e_ratio:        0.05
  curr_ratio:       0.03
  quick_ratio:      0.03
  z_score:          0.10
  no_y_pos_eps:     0.02
  no_y_pos_fcf:     0.02
  shares_chg:       0.02
  pe_ratio:         0.02
  ps_ratio:         0.02
  pb_ratio:         0.02
  ev_ebitda:        0.02
  beta:             0.02
  scaled_vol:       0.02
  accrual_rat:      0.02
  cash_conv_rat:    0.02
############################################################ QUALITATIVE #############################################
quant_moat_params:
    Gross margin: 0.4
    ROIC: 0.15
    
# Scores related to reaching Quant MOAT measures
quant_moat_scores:
    Gross margin: 5
    ROIC: 5
    
# !!! RETHINK THE WORDS THAT MAY ACTUALLY INDICATE MOAT OR LEADERSHIP STRENGTH
# !!! ADD POLISH COUNTERPARTS
# MOAT keywords
moat_keywords:
     'patent|trademark|brand|loyalty|network effect|switching costs|economies of scale|scale benefits|proprietary technology|regulatory advantage|most successful|the best source|best-in-class'
# Leadership network keywords
leadership_keywords:
    'innovative|innovation|innovations|experienced|veteran|visionary|strategic|leadership|board of directors|revolutionary|revolutionized|unmatched|massive scale'

# Management strength parametrization
keyword_score_weight: 1 
sentiment_score_weight: 40

# Qualitiative scoreard weights
# !!! THINK ABOUT THE WEIGHTS
qual_scorecard_weights:
    MOAT_TEXT  : 0.3
    MOAT_QUANT : 0.4
    MANAGEMENT : 0.15
    SENTIMENT  : 0.15   

# Transcripts to pull for qualitative analysis
transcript_urls:
  MSFT: "https://www.microsoft.com/en-us/investor/events/fy-2025/earnings-fy-2025-q4"
  AAPL: "https://www.fool.com/earnings/call-transcripts/2025/08/01/apple-aapl-q3-2025-earnings-call-transcript/"
  TSLA: "https://www.fool.com/earnings/call-transcripts/2025/07/23/tesla-tsla-q2-2025-earnings-call-transcript/"
  GOOGL: "https://www.fool.com/earnings/call-transcripts/2025/07/23/alphabet-googl-q2-2025-earnings-call-transcript/"
  AMZN: "https://www.fool.com/earnings/call-transcripts/2025/02/06/amazoncom-amzn-q4-2024-earnings-call-transcript/"
  NVDA: "https://www.fool.com/earnings/call-transcripts/2025/02/26/nvidia-nvda-q4-2025-earnings-call-transcript/"
  META: "https://www.fool.com/earnings/call-transcripts/2025/01/29/meta-platforms-meta-q4-2024-earnings-call-transcri/"
  ASML: "https://www.fool.com/earnings/call-transcripts/2021/10/21/asml-holding-nv-asml-q3-2021-earnings-call-transcr/"
  AMD: "https://www.fool.com/earnings/call-transcripts/2025/02/05/advanced-micro-devices-amd-q4-2024-earnings-call-t/"
  ARM: "https://www.fool.com/earnings/call-transcripts/2025/02/05/arm-holdings-arm-q3-2025-earnings-call-transcript/"
  JPM: "https://www.fool.com/earnings/call-transcripts/2025/08/04/jpmorgan-jpm-q2-2025-earnings-call-transcript/"
  GS: "https://www.fool.com/earnings/call-transcripts/2025/07/16/goldman-sachs-gs-q2-2025-earnings-call-transcript/"
  INTU: "https://www.fool.com/earnings/call-transcripts/2025/08/21/intuit-intu-q4-2025-earnings-call-transcript/"
  VRTX: "https://www.fool.com/earnings/call-transcripts/2025/02/10/vertex-pharmaceuticals-vrtx-q4-2024-earnings-call/"
  C: "https://www.fool.com/earnings/call-transcripts/2025/07/15/citigroup-c-q2-2025-earnings-call-transcript/"
  KMI: "https://www.fool.com/earnings/call-transcripts/2025/07/17/kinder-morgan-kmi-q2-2025-earnings-call-transcript/"
  LMT: "https://www.fool.com/earnings/call-transcripts/2025/07/22/lockheed-martin-lmt-q2-2025-earnings-transcript/"
  BATS.L: "https://www.fool.com/earnings/call-transcripts/2025/02/13/british-american-tobacco-plc-bti-q4-2024-earnings/"
  INTC: "https://www.fool.com/earnings/call-transcripts/2025/08/05/intel-intc-q2-2025-earnings-call-transcript/"
  BABA: "https://www.fool.com/earnings/call-transcripts/2025/02/20/alibaba-group-baba-q4-2024-earnings-call-transcrip/"
  RIO: "https://www.fool.com/earnings/call-transcripts/2025/02/19/rio-tinto-group-rio-q4-2024-earnings-call-transcri/"
  EQR: "https://www.stockinsights.ai/us/EQR/earnings-transcript/fy25-q2-0f69"
  TSMC34.SA: "https://www.fool.com/earnings/call-transcripts/2025/01/16/taiwan-semiconductor-manufacturing-tsm-q4-2024-ear/"
  RACE: "https://www.insidermonkey.com/blog/ferrari-n-v-nyserace-q4-2024-earnings-call-transcript-1443440/"
  PLTR: "https://www.fool.com/earnings/call-transcripts/2025/02/04/palantir-technologies-pltr-q4-2024-earnings-call-t/"
  LLY: "https://www.fool.com/earnings/call-transcripts/2025/02/06/eli-lilly-lly-q4-2024-earnings-call-transcript/"
  CRM: "https://www.fool.com/earnings/call-transcripts/2025/02/26/salesforce-crm-q4-2025-earnings-call-transcript/"
  ORCL: "https://www.fool.com/earnings/call-transcripts/2025/03/10/oracle-orcl-q3-2025-earnings-call-transcript/"
  V: "https://www.fool.com/earnings/call-transcripts/2024/10/29/visa-v-q4-2024-earnings-call-transcript/"
  MA: "https://www.fool.com/earnings/call-transcripts/2022/07/28/mastercard-ma-q2-2022-earnings-call-transcript/"
  DELL: "https://www.fool.com/earnings/call-transcripts/2021/02/26/dell-technologies-inc-dell-q4-2021-earnings-call-t/"
  NOW: "https://www.fool.com/earnings/call-transcripts/2022/01/27/service-now-now-q4-2021-earnings-call-transcript/"
  UBER: "https://www.fool.com/earnings/call-transcripts/2025/02/05/uber-technologies-uber-q4-2024-earnings-call-trans/"
  CRWD: "https://www.fool.com/earnings/call-transcripts/2021/06/03/crowdstrike-holdings-inc-crwd-q1-2022-earnings-cal/"
  SAP: "https://www.fool.com/earnings/call-transcripts/2021/10/21/sap-se-sap-q3-2021-earnings-call-transcript/"
  BKNG: "https://www.nasdaq.com/articles/booking-holdings-bkng-q4-2024-earnings-call-transcript"
  CMG: "https://www.nasdaq.com/articles/chipotle-mexican-grill-cmg-q4-2024-earnings-call-transcript"
  ADYEN.AS: "https://www.fool.com/earnings/call-transcripts/2020/02/27/adyen-nv-adyyf-q2-2019-earnings-call-transcript.aspx"
  XYZ: "https://www.fool.com/earnings/call-transcripts/2025/02/21/block-xyz-q4-2024-earnings-call-transcript/"
  SE: "https://www.fool.com/earnings/call-transcripts/2025/03/04/sea-limited-se-q4-2024-earnings-call-transcript/"
  ADBE: "https://www.fool.com/earnings/call-transcripts/2025/06/13/adobe-adbe-q2-2025-earnings-call-transcript/"
  ANET: "https://www.fool.com/earnings/call-transcripts/2025/02/18/arista-networks-anet-q4-2024-earnings-call-transcr/"
  AZO: "https://www.stockinsights.ai/us/AZO/earnings-transcript/fy25-q2-df99"
  BN: "https://www.insidermonkey.com/blog/brookfield-corporation-nysebn-q2-2024-earnings-call-transcript-1332472/"
  CCJ: "https://www.cameco.com/invest/financial-information/quarterly-reports/2025/q2"
  COIN: "https://www.fool.com/earnings/call-transcripts/2025/02/13/coinbase-global-coin-q4-2024-earnings-call-transcr/"
  CSU.TO: "https://quartr.com/companies/constellation-software-inc_3613"
  NVO: "https://www.fool.com/earnings/call-transcripts/2025/02/05/novo-nordisk-nvo-q4-2024-earnings-call-transcript/"
  HIMS: "https://www.stockinsights.ai/us/HIMS/earnings-transcript/fy24-q4-0314"
  INPST.AS: "https://inpost.co.uk/resources/inpost-group-q1-2025-results"
  MELI: "https://www.fool.com/earnings/call-transcripts/2025/02/20/mercadolibre-meli-q4-2024-earnings-call-transcript/"
  MU: "https://www.fool.com/earnings/call-transcripts/2025/06/25/micron-mu-q3-2025-earnings-call-transcript/"
  PYPL: "https://www.fool.com/earnings/call-transcripts/2025/08/06/paypal-pypl-q2-2025-earnings-call-transcript/"
  RHM.DE: "https://www.rheinmetall.com/en/media/news-watch/news/2025/08/2025-08-07-rheinmetall-news-half-yearly-financial-report-h1"
  SPOT: "https://www.fool.com/earnings/call-transcripts/2025/08/04/spotify-spot-q2-2025-earnings-call-transcript/"
  UBER: "https://www.fool.com/earnings/call-transcripts/2025/02/05/uber-technologies-uber-q4-2024-earnings-call-trans/"
  ULTA: "https://www.fool.com/earnings/call-transcripts/2025/03/14/ulta-beauty-ulta-q4-2024-earnings-call-transcript/"
  OR.PA: "https://www.loreal-finance.com/eng/press-release/2025-half-year-results"
  MCD: "https://www.fool.com/earnings/call-transcripts/2025/02/10/mcdonalds-mcd-q4-2024-earnings-call-transcript/"
  SBUX: "https://www.fool.com/earnings/call-transcripts/2025/08/05/starbucks-sbux-q3-2025-earnings-call-transcript/"
  NKE: "https://www.fool.com/earnings/call-transcripts/2025/03/20/nike-nke-q3-2025-earnings-call-transcript/"
  ODFL: "https://www.fool.com/earnings/call-transcripts/2025/07/30/old-dominion-odfl-q2-2025-earnings-transcript/"
  PANW: "https://www.fool.com/earnings/call-transcripts/2025/02/13/palo-alto-networks-panw-q2-2025-earnings-call-tran/"
  ZAL.DE: "https://www.fool.com/earnings/call-transcripts/2020/05/10/zalando-se-zlndy-q1-2020-earnings-call-transcript.aspx"
  KER.PA: "https://finance.yahoo.com/news/kering-sa-ppruf-h1-2025-071449242.html"
  MC.PA: "https://www.insidermonkey.com/blog/lvmh-moet-hennessy-louis-vuitton-societe-europeenne-pnklvmuy-q2-2024-earnings-call-transcript-1326880/"
  AZN: "https://www.fool.com/earnings/call-transcripts/2025/02/06/astrazeneca-plc-azn-q4-2024-earnings-call-transcri/"
  UNH: "https://www.fool.com/earnings/call-transcripts/2025/08/06/unitedhealth-unh-q2-2025-earnings-transcript/"
  BAC: "https://www.fool.com/earnings/call-transcripts/2025/07/16/bofa-bac-q2-2025-earnings-call-transcript/"

############################################################ EXTERNAL ############################################
# Input to parse pdf from Cymcyk analysis (map tickers to actual names used)
ticker_mapping:
  MSFT: Microsoft
  AAPL: Apple
  GOOGL: Alphabet
  META: Meta Platform
  AMZN: Amazon
  NVDA: Nvidia
  INTU: Intuit
  TSMC34.SA: TSMC
  ASML: ASML
  BABA: Alibaba
  PLTR: Palantir
  AMD: AMD
  RACE: Ferrari
  C: Citi
  GS: Goldman Sachs
  LMT: Lockheed Martin
  VRTX: Vertex Pharmaceuticals
  KMI: Kinder Morgan
  RIO: Rio Tinto
  EQR: Equity Residential
  INTC: Intel
  LLY: Eli Lilly
  TSLA: Tesla
  ARM: ARM
  JPM: Jp Morgan Chase
  BATS.L: British American Tobacco
  ADYEN.AS: Adyen
  XYZ: Block
  CRM: Salesforce
  SE: Sea Limited
  ORCL: Oracle
  ADBE: Adobe
  V: Visa
  MA: Mastercard
  ANET: Arista Networks
  AZO: AutoZone
  BKNG: Booking
  BN: Brookfield Corporation
  CCJ: Cameco Corp
  COIN: Coinbase
  CSU.TO: Constellation Software
  DELL: Dell
  NVO: Novo Nordisk
  HIMS: Hims & Hers
  INPST.AS: Inpost
  MELI: Mercadolibre
  MU: Micron Technology
  PYPL: PayPal
  RHM.DE: Rheinmetall
  NOW: ServiceNow
  SPOT: Spotify
  UBER: Uber
  ULTA: Ulta Beauty
  CMG: ChipotleMexican Grill
  CRWD: Crowdstrike
  OR.PA: L'oreal
  MCD: McDonalds
  SBUX: Starbucks
  NKE: Nike
  ODFL: Old Dominion Freight Line
  PANW: Palo Alto
  ZAL.DE: Zalando
  KER.PA: Kering
  MC.PA: LVMH
  SAP: SAP
  AZN: Astra Zeneca
  UNH: United Healthcare
  BAC: Bank of America
  
pdf_path:
  'input\StockScan_grudzien_2024_fin-laqvwb.pdf'